quarkus.azure-functions.app-name=func-az-deploy-test
quarkus.azure-functions.runtime.java-version=25
quarkus.http.root-path=/api

app.segredo-teste=${kv//TESTE}
app.jwt-private-key=${kv//jwt-private-key}
app.jwt-public-key=${kv//jwt-public-key}